# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  checkout-code:
  docker:
    - image: circleci/ubuntu:latest
    - run: 
        command: |
          sleep 13
          echo "checkout job"
  lint:
    docker:
      - image: circleci/ubuntu:latest
    steps:
      - run: 
          command: |
            sleep 1m
            sleep 5
            echo "lint job"
  build:
    docker:
      - image: circleci/ubuntu:latest
    steps:
      - run: 
          command: |
            sleep 2m
            sleep 3
            echo "build job"
  deploy-static-preview:
    docker:
      - image: circleci/ubuntu:latest
    steps:
      - run: 
          command: |
            sleep 17
            echo "deploy static preview job"
  unit-test:
    docker:
      - image: circleci/ubuntu:latest
    steps:
      - run:
          command: |
            sleep 57
            echo "unit testing job"
  e2e:
    docker:
      - image: circleci/ubuntu:latest
    steps:
      - run:
          command: |
            sleep 1m
            sleep 18
            echo "end to end test job"
  deploy-approval:
    type: approval
  deploy:
    docker:
      - image: circleci/ubuntu:latest
    steps:
      - run:
          command: |
            sleep 9
            echo "deploy job"
  
workflows:
  # Name the workflow "Welcome"
  fooWorkflow:
    # Run the welcome/run job in its own container
    jobs:
      - checkout-code
      - build:
          requires:
           - checkout-code
      - lint:
          requires:
            - checkout-code
      - unit-test:
          requires:
            - build
      - e2e:
          requires:
            - build
      - deploy-static-preview:
          requires:
            - build
      - deploy-approval:
          requires:
            - unit-test
            - e2e
      - deploy:
          requires:
            - deploy-approval
